# Generated by Django 3.0 on 2021-08-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcle',
            new_name='Article',
        ),
    ]
