version: "3"
   
services:
  postgresdb:
    container_name: cms-postgresdb
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: cms-pgadmin
    ports:
      - 2222:2222
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 2222
    networks:
      - postgres_db
    # restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - postgres_db
      - web

networks:
  postgres_db:
    driver: bridge
  web:
    external: true