version: "3"
   
services:
  postgresdb:
    container_name: cms-postgresdb
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres_db
    volumes:
      - /var/docker-data/cms-backsoul-db-data:/var/lib/postgresql/data/pgdata
    

  pgadmin:
    image: dpage/pgadmin4
    container_name: cms-pgadmin
    ports:
      - 2222:2222
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 2222
    networks:
      - postgres_db
    # restart: unless-stopped

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cms-backsoul
    ports:
      - 8000:8000
    depends_on: 
      - postgresdb
    networks:
      - postgres_db
      - web
    volumes:
      - cms-backsoul-web-data:/var/lib/cms-backsoul

volumes:
  cms-backsoul-web-data:

networks:
  postgres_db:
    driver: bridge
  web:
    external: true